language: php

php:
  - 5.6

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - composer self-update
  - cd ./tests/laravel
  - composer update

script: "vendor/bin/phpunit"
